<?php

declare(strict_types=1);

require_once __DIR__ . '/../includes/bootstrap.php';

require_login();

$user = current_user();
if (($user['role'] ?? '') !== 'admin') {
    http_response_code(403);
    exit('Database backup is available only to the user administrator.');
}

if (user_requires_totp($user) && !user_has_totp_enabled($user)) {
    http_response_code(403);
    exit('Complete authenticator setup before downloading a database backup.');
}

if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    http_response_code(405);
    header('Allow: POST');
    exit('Method not allowed.');
}

try {
    verify_csrf();
} catch (RuntimeException $exception) {
    http_response_code(403);
    exit('Invalid or expired session token.');
}

/**
 * Wrap a MySQL identifier safely for statements returned by SHOW commands.
 */
function backup_identifier(string $identifier): string
{
    return '`' . str_replace('`', '``', $identifier) . '`';
}

/**
 * Convert a database value to a portable SQL literal.
 */
function backup_sql_literal(PDO $pdo, mixed $value): string
{
    if ($value === null) {
        return 'NULL';
    }

    $quoted = $pdo->quote((string) $value);
    if ($quoted === false) {
        throw new RuntimeException('Unable to encode a value for the database backup.');
    }

    return $quoted;
}

/**
 * Send a line to the download without retaining the complete dump in memory.
 */
function backup_write(string $text = ''): void
{
    echo $text . "\n";
}

try {
    $pdo = database();
    $settings = database_settings();
    $databaseName = (string) ($settings['name'] ?? 'nusace_bulletin');
    $filename = 'nusace-bulletin-backup-' . date('Y-m-d-His') . '.sql';

    header('Content-Type: application/sql; charset=utf-8');
    header('Content-Disposition: attachment; filename="' . $filename . '"');
    header('Cache-Control: no-store, no-cache, must-revalidate, max-age=0');
    header('Pragma: no-cache');
    header('X-Content-Type-Options: nosniff');

    backup_write('-- NU Lipa SACE Bulletin database backup');
    backup_write('-- Database: ' . str_replace(["\r", "\n"], '', $databaseName));
    backup_write('-- Generated: ' . date(DATE_ATOM));
    backup_write('-- Generated by: ' . str_replace(["\r", "\n"], '', (string) ($user['username'] ?? 'admin')));
    backup_write();
    backup_write('SET NAMES utf8mb4;');
    backup_write('SET FOREIGN_KEY_CHECKS = 0;');
    backup_write();

    $pdo->exec('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');
    $pdo->beginTransaction();

    $tableStatement = $pdo->query('SHOW FULL TABLES WHERE Table_type = \'BASE TABLE\'');
    $tables = [];
    while (($tableRecord = $tableStatement->fetch(PDO::FETCH_NUM)) !== false) {
        $tables[] = (string) $tableRecord[0];
    }

    foreach (array_reverse($tables) as $tableName) {
        backup_write('DROP TABLE IF EXISTS ' . backup_identifier($tableName) . ';');
    }
    backup_write();

    foreach ($tables as $tableName) {
        $createStatement = $pdo->query('SHOW CREATE TABLE ' . backup_identifier($tableName));
        $createRecord = $createStatement->fetch(PDO::FETCH_NUM);
        if ($createRecord === false || !isset($createRecord[1])) {
            throw new RuntimeException('Unable to read the structure for table ' . $tableName . '.');
        }

        backup_write('--');
        backup_write('-- Table structure for ' . backup_identifier($tableName));
        backup_write('--');
        backup_write((string) $createRecord[1] . ';');
        backup_write();

        $dataStatement = $pdo->query('SELECT * FROM ' . backup_identifier($tableName));
        $wroteDataHeader = false;
        while (($row = $dataStatement->fetch(PDO::FETCH_ASSOC)) !== false) {
            if (!$wroteDataHeader) {
                backup_write('--');
                backup_write('-- Data for ' . backup_identifier($tableName));
                backup_write('--');
                $wroteDataHeader = true;
            }

            $columns = array_map(
                static fn (string $column): string => backup_identifier($column),
                array_keys($row)
            );
            $values = array_map(
                static fn (mixed $value): string => backup_sql_literal($pdo, $value),
                array_values($row)
            );
            backup_write(
                'INSERT INTO ' . backup_identifier($tableName)
                . ' (' . implode(', ', $columns) . ') VALUES ('
                . implode(', ', $values) . ');'
            );
        }

        if ($wroteDataHeader) {
            backup_write();
        }
    }

    $pdo->commit();
    backup_write('SET FOREIGN_KEY_CHECKS = 1;');
    exit;
} catch (Throwable $exception) {
    if (isset($pdo) && $pdo instanceof PDO && $pdo->inTransaction()) {
        $pdo->rollBack();
    }

    if (!headers_sent()) {
        http_response_code(500);
        header('Content-Type: text/plain; charset=utf-8');
    }

    exit('Unable to generate the database backup. Please try again or contact the site administrator.');
}
